============================================================================
Fill-out this form, rename the file to yer name and zip it. Then Upload yer
application in Privite to TGS.    Thanx......ProTurbo 
============================================================================

Before you start filling out the application form, make sure that you
are very serious about it. All I'm saying is do not waste my time.


            R A B N E T   A P P L I C A T I O N   F O R M
            ---------------------------------------------


1. What is yer alias?

______________________________________________


2. What is yer real name?

______________________________________________


3. What is the name and number of yer board?

______________________________________________


4. What is the name of the software you are running.

______________________________________________



5. How long have you been running yer board?

______________________________________________


6. How many users you have on?

______________________________________________


7. Are you affiliated with any group. If YES name them.

______________________________________________

______________________________________________


8. Is yer board specializing in something? If so Explain.

______________________________________________

______________________________________________


9. List Conferences you would like to NET or you would like to see.

______________________________________________

______________________________________________

______________________________________________

______________________________________________


10. What is yer voice number, so we can talk about RABNET.

______________________________________________


11. Name a few users I can talk too for references.

______________________________________________

______________________________________________


12. Are you Netting with anyone right now? If so name them.

______________________________________________

______________________________________________

______________________________________________


13. Why would you like to NET with us, Explain.

______________________________________________

______________________________________________

______________________________________________

______________________________________________





Well this is it man, basically we are looking for quality
LD boards. We want to spread the word, exchange (programing)
ideas and meet users.


TGS is:
-------

- RABID World HQ
- RABNET Host Network
- IPXnet Region (416)
- Unprotected Programs 
- Specializing in Virus/Trojan
- 650 Meg Online
- USR 14.4 v42 bis
- P/H/A Support