echo off
cls
echo VRI Newsletter #1
echo:
echo Viral Research International
echo Ready To Print.... Turn Printer On Now.....
pause
copy vri#1-1.txt prn
copy vri#1-2.txt prn
copy vri#1-3.txt prn
copy vri#1-4.txt prn
copy vri#1-5.txt prn
copy vri#1-6.txt prn
cls
echo VRI Application
echo:
echo Advance Paper To Beginning Of Page
echo:
echo Ready To Print Application
pause
copy vri#1-7.txt prn
cls
echo VRI - Viral Research International Newsletter #1
echo:
echo Print Complete
echo:
echo on
